version: "3.8"

services:
  products_service:
    build:
      context: ./ProductsDataService
    restart: always
    ports:
      - 5001:5001
    volumes:
      - ./ProductsDataService:/app2
  users_service:
    build:
      context: ./UsersDataService
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./UsersDataService:/app
